### ISSUE TITLE
Is there a version for Gradle around?

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/vertx-docgen#15]
Nice project, this one! I would like to use it with Gradle. Are you aware of any versions doing that?
For `javadoc to asciidoc` I found this as well https://github.com/asciidoctor/asciidoclet

**Comment by sczyh30** [comment]
Hi, docgen in fact is an annotation processor so you can use it in Gradle by providing processor `compilerArgs`. An example for the given [test_proj example](https://github.com/vert-x3/vertx-docgen/tree/master/test-proj) in the project:

```gradle
plugins {
  id 'java'
}

version '1.0-SNAPSHOT'

ext {
  vertxVersion = "3.3.2"
}

repositories {
  jcenter()
}

task docProcessing(type: JavaCompile, group: 'build') {
  source = sourceSets.main.java
  classpath = configurations.compile
  destinationDir = project.file('src/main/asciidoc')
  options.compilerArgs = [
    "-proc:only",
    "-processor", "io.vertx.docgen.JavaDocGenProcessor",
    "-Adocgen.output=${project.buildDir}/asciidoc",
    "-Adocgen.source=${project.projectDir}/src/main/asciidoc/doc.adoc"
  ]
}

compileJava {
  targetCompatibility = 1.8
  sourceCompatibility = 1.8

  dependsOn docProcessing
}

dependencies {
  compile("io.vertx:vertx-docgen:${vertxVersion}")
}
```

The task `docProcessing` is responsible for generating docs.

**Comment by aschrijver** [comment]
Thanks a bunch! Exactly what I was looking for :+1:

**Comment by aschrijver** [comment]
Would be nice to add this piece of information to the README. Could you PR (I can too, if you lack the time)?

One more thing: Presumably this can be improved by adding docgen dependency to `provided` scope, so the docgen does not end up in your shipped runtime (like http://stackoverflow.com/questions/10405970/how-do-i-define-a-compile-time-only-classpath-in-gradle)

**Comment by sczyh30** [comment]
Yes, I'll make a PR to add examples about Gradle.

Using `provided` scope is a good idea and Gradle start supporting compile time only dependencies (`compileOnly`) from Gradle 2.12 (see [here](https://gradle.org/blog/compile-only-dependencies/)) so I think we can use the original `compileOnly` scope here :-)

**Comment by aschrijver** [comment]
Cross-post, sorry.

**Comment by aschrijver** [comment]
Just changing to `compileOnly` does not seem to work out of the box:
```
error: Annotation processor 'io.vertx.docgen.JavaDocGenProcessor' not found
warning: Annotation processing without compilation requested but no processors were found.
```
Will check later, going for `compile` for now.

**Comment by sczyh30** [comment]
The `classpath` in task `docProcessing` should also be changed:

```gradle
classpath = configurations.compile + configurations.compileOnly
```

**Comment by aschrijver** [comment]
Ah, you're right. Thanks again!!

**Comment by aschrijver** [comment]
Still get `warning: The following options were not recognized by any processor: '[docgen.source]'` so presumably I also have to set that as a resource root. If so, then it should be added to the example.

**Comment by vietj** [comment]
fancy doing a PR for the example with gradle in `test-proj` ?

**Comment by vietj** [comment]
never mind there is one

**Comment by aschrijver** [comment]
@sczyh30 Do you get aforementioned warning, or did I overlook something?

**Comment by sczyh30** [comment]
@aschrijver Yes, I've also got the same warning... What's wrong with it?

**Comment by aschrijver** [comment]
Seems like something doesn't work as it should..

**Comment by vietj** [comment]
can you provide a reproducer @aschrijver ?

**Comment by aschrijver** [comment]
Yes, `gradle clean build` this project and you should see it: https://github.com/engagingspaces/vertx-dataloader/commit/92249437eb5db4bb562c54fd7d1a35398be60914
