### ISSUE TITLE
source java code inclusion: how to get the `import` statements

### ISSUE THREAD

**Issue by k33g** [vert-x3/vertx-docgen#23]
If I write this:
```
[source,java]
----
{@link cookbook.microservices.first.step01.FirstMicroService}
----
```
I get only the source code of the class, but I would like to display the needed packages too

**Comment by tsegismont** [comment]
How about including the file as-is with Asciidoc include directive?

That would not translate the code of course, but it seems you only need
Java source?

2017-07-03 10:10 GMT+02:00 Philippe Charrière <notifications@github.com>:

**Comment by k33g** [comment]
@tsegismont you're right, it's a very good idea (I don't know yet Asciidoc)
thx

**Comment by vietj** [comment]
@tsegismont we need to think if the cookbook will be or not polyglot before making such assumption

**Comment by tsegismont** [comment]
Yes, hence the question tag :)

2017-07-04 7:46 GMT+02:00 Julien Viet <notifications@github.com>:
