### ISSUE TITLE
Is there (or will there be) a 3.6.3 release of vertx-docgen?

### ISSUE THREAD

**Issue by chefhoobajoob** [vert-x3/vertx-docgen#34]
Vertx codegen/codetrans seem to be advancing with the rest of the vertx libs for each release, but the latest release of docgen [I can find](https://mvnrepository.com/artifact/io.vertx/vertx-docgen/3.5.1) is 3.5.1. Is that correct? Is this library still active? We're using it for documenting our internal polyglot api's.

**Comment by vietj** [comment]
the library is still active but now it is released independantly of the Vert.x stack because it is used in other projects. So now the latest release is 0.9.2
